name: lear-github-action
run-name: ${{ github.actor }} is learning GitHub Actions
on: 
  push:
    branches:
      - main
  schedule:
    - cron: '5 * * * *'
jobs: 
  build:
    runs-on: 
       labels:
         runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Run onle line-script
        run: 'Hello World'
        
      
       
